name: Build Swift Binary

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Swift
        run: |
          brew install swift

      - name: Build Swift Script
        run: |
          swiftc -target x86_64-apple-macos10.15 -o ocr-x86_64-apple-darwin main.swift
          swiftc -target arm64-apple-macos11 -o ocr-aarch64-apple-darwin main.swift

      - name: Test
        run: ./ocr-x86_64-apple-darwin $(pwd)/test.jpg auto

      - name: CodeSign
        run: |
          # 设置证书
          echo "${{ secrets.APPLE_CERTIFICATE }}" | base64 --decode > cert.p12
          security create-keychain -p github-actions github-actions.keychain
          security default-keychain -s github-actions.keychain
          security unlock-keychain -p github-actions github-actions.keychain
          security import cert.p12 -k github-actions.keychain -P "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k github-actions github-actions.keychain

          codesign --force \
            -s "${{ secrets.APPLE_SIGNING_IDENTITY }}" \
            --keychain github-actions.keychain \
            --options runtime \
            --timestamp \
            ./ocr-x86_64-apple-darwin

          codesign --force \
            -s "${{ secrets.APPLE_SIGNING_IDENTITY }}" \
            --keychain github-actions.keychain \
            --options runtime \
            --timestamp \
            ./ocr-aarch64-apple-darwin

          # 验证签名
          codesign -dvv ./ocr-aarch64-apple-darwin
          codesign -d --entitlements :- ./ocr-aarch64-apple-darwin

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ocr-x86_64-apple-darwin
          path: ./ocr-x86_64-apple-darwin

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ocr-aarch64-apple-darwin
          path: ./ocr-aarch64-apple-darwin
